# Python CircleCI 2.0 configuration file
version: 2.1
orbs:
  node: circleci/node@5.0.0
  gh: circleci/github-cli@2.0.0
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies and app
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            . venv/bin/activate
            pip install .
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            flake8 --exclude=venv*,__init__.py --statistics
            pytest -v --cov
            schedulecheck -m 1 -t 1
            schedulecheck -m 2 -t 1
workflows:
  test-and-release:
    jobs:
      - build
      - gh/release:
          notes-file: README.md
          tag: 1.0.0 
          title: The initial release
          requires:
            - build
          context:
            - GITHUB_CREDS
          filters:
            branches:
              only:
                - develop
